# Array Method

In [79]:
import numpy as np
from numpy import array

# ndim

In [80]:
arr = array(([3,2,45,3],
            [3,2,3,6]))

arr = np.random.randint(1,5, size=((3,3)))
arr.ndim  


# arr = array((([3,2,4],[3,2,4],[3,2,34],[4,3,9]), ([3,2,3],[5,6,4],[5,3,2],[6,7,5]), ([5,3,2],[6,7,5],[3,2,4],[3,2,4])))
# arr
arr_n = np.arange(1,501).reshape((5,10,10))
arr_n.ndim

np.max(arr_n.sum(axis=2))

np.int64(4955)

# shape

In [81]:
arr.shape

(3, 3)

# size

In [82]:
arr.size # It gives total number of elements of 1D array

9

# dtype

# Priority order:    string -> complex -> float -> integer -> bool


In [83]:
arr_strr = array((['Computer','Machine','Kernal'],
                     ['array','operator','python']), )

arr_strr.dtype
# print(arr_strr.dtype.str.capitalize())


arr = array(([True , 3,3.3, 3+3j, 'string']))
arr.dtype

arr = array(([2,3,4],
             ['computer','memory','data']))
# arr.dtype.char

# arr.dtype.byteorder

# arr.dtype.fields

# arr.dtype.type

# arr.dtype.str
type(arr.dtype.name) is str  # -> True

True

# ndarray Method -->  Array Conversion

tolist(): The contents of data stored into nested list.

In [84]:
arr = array(([3,2,1,4,34,32,2],
            [34,2,34,2,34,43,6]))
arr.tolist()

[[3, 2, 1, 4, 34, 32, 2], [34, 2, 34, 2, 34, 43, 6]]

item(): It returns standard Python scalar object

In [85]:
arr = array(([3,2,1,4,34,32,2],
            [34,2,34,2,34,43,6]))

arr.item(5)

32

In [86]:
arr = array(([4,2,2,90,32],
            [3,2,45,56,32]), dtype=np.int32)
binary_data = arr.tobytes()  #-> encode data (str -> ' ') 

# decode
" ".join(map(str, binary_data))

arr.itemsize 
r,c = (arr.strides)
np.multiply(r,c)
# arr.dtype.type

np.int64(80)

# tobytes

It used to much more efficient and safty with data

In [87]:
data = arr.tobytes(order='C') # row-wise data
' '.join(map(str, data))

data = arr.tobytes(order='F') # column-wise data
' '.join(map(str, data))

'4 0 0 0 3 0 0 0 2 0 0 0 2 0 0 0 2 0 0 0 45 0 0 0 90 0 0 0 56 0 0 0 32 0 0 0 32 0 0 0'

# tofile

In [88]:
data = array(([4,2,2,90,32],
            [3,2,45,56,32],
            [12,2,33,3,4]))

data.tofile('file.txt', sep=',', format='%0d')


In [89]:
with open('file.txt')as f:
    data = f.readline().split(',')

data = array([int(n) for n in data])
np.mean(data)

np.float64(21.466666666666665)

# dump

It is used to seriallization(pickling) means it is a process to converting Python object hierarchy to binary byte stream.
It help to save file and later reconstructed file like list, dictionary and Machine Learning Model.  
Uses Pickle to byte stream or file.

In [90]:
import pickle
data = {"Model":321,
        'MonoDB':"SQL Lite",
        'Byte':'Bit',
        'Serialization':'Pickling'}

with open('file_binaray_data.pkl', 'wb')as file:
    pickle.dump(data, file, 2)

with open('file_binaray_data.pkl', 'rb')as file:
    loaded_file = pickle.load(file)

print(loaded_file)

{'Model': 321, 'MonoDB': 'SQL Lite', 'Byte': 'Bit', 'Serialization': 'Pickling'}


# dumps

It returns serialized or pickled as a binary bytes stream data  or binary raw bytes data.

In [91]:
pickle.dumps(loaded_file,2)


b'\x80\x02}q\x00(X\x05\x00\x00\x00Modelq\x01MA\x01X\x06\x00\x00\x00MonoDBq\x02X\x08\x00\x00\x00SQL Liteq\x03X\x04\x00\x00\x00Byteq\x04X\x03\x00\x00\x00Bitq\x05X\r\x00\x00\x00Serializationq\x06X\x08\x00\x00\x00Picklingq\x07u.'

# astype(data, dtype)

It used set the data type of an array. 

We can change the data type of array

In [92]:
data = array(([4,2,2,90,32],
            [3,2,45,56,32],
            [12,2,33,3,4]))
np.astype(data, np.float64)
np.astype(data, np.int64)
data.item(0)

4

# byteswap(bool)

It reverses the bytes order of each elements in an array.

Its matter in ML and systems:
>> Reading larger binary dataset of Machine model.
>> Loading the model weights from other architectures.

This matters in computer, Computers store numbers using endianness:

● Little-endian: Lowest/least significant byte stored first.

● Big-endian: Highest/most significant byte stored first.

● < : little endian

● > : big endian

● = : native

In [93]:
data = array([1,2], dtype=np.int16)  # 2-bytes = 16-bits (1byte = 8bits -> 00000001) 
data.byteswap(False)
# data.dtype.byteorder

array([256, 512], dtype=int16)

# copy()

It returns copy of original array. 

It preserved data type whether or not data is byteswapped.

In [94]:
data = array(([4,2,2,90,32],
            [3,2,45,56,32],
            [12,2,33,3,4],
            [3,2,45,56,32],
            [12,2,33,3,4]), dtype=np.int32)

data_copy = data.copy()
data_copy
# data_copy[2] = 900
# data_copy.dtype

array([[ 4,  2,  2, 90, 32],
       [ 3,  2, 45, 56, 32],
       [12,  2, 33,  3,  4],
       [ 3,  2, 45, 56, 32],
       [12,  2, 33,  3,  4]], dtype=int32)

# view()
It reinterprets the same memory bits as different data type  (like int, float, uint8, uint16, uint32, uint64, bool).

That matters when reading binary raw data, hardware data stream, image processing, network packets.

In [95]:
# data_copy.view(dtype=np.int64)  # argument as data type desicriptor gives -> new array same as self
data_copy.view(np.single).shape
data_copy.view(np.ubyte)  # returns an array with how many bytes each element consists 


array([[ 4,  0,  0,  0,  2,  0,  0,  0,  2,  0,  0,  0, 90,  0,  0,  0,
        32,  0,  0,  0],
       [ 3,  0,  0,  0,  2,  0,  0,  0, 45,  0,  0,  0, 56,  0,  0,  0,
        32,  0,  0,  0],
       [12,  0,  0,  0,  2,  0,  0,  0, 33,  0,  0,  0,  3,  0,  0,  0,
         4,  0,  0,  0],
       [ 3,  0,  0,  0,  2,  0,  0,  0, 45,  0,  0,  0, 56,  0,  0,  0,
        32,  0,  0,  0],
       [12,  0,  0,  0,  2,  0,  0,  0, 33,  0,  0,  0,  3,  0,  0,  0,
         4,  0,  0,  0]], dtype=uint8)

# getfield()

Using getfield, we could extract fixed length of substring from an array of string.

In [96]:
data_str = array(['MongoDB', 'Protocol', 'Binary-Data'])
dataf = data_str.getfield('S3',2)


# setflags(write=None, align=None, uic=None)

If data is aligned in memory addresses so that CPU's can access data very efficiently.

In other word, if aligned is True so that allows CPU's that can access data very efficiently.

In [97]:
data.setflags(write=True, align=False)
data[4] = [9,0,8,90,0]
data.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : False
  WRITEBACKIFCOPY : False

# fill(scalar)

fill scalar value = replace all elements with one constant value 

In [98]:
data = np.random.randint(1,10, size=((5,5)))

data[[1,2,3],1:4] = 0
data[2,2] = 1
data

array([[3, 1, 2, 1, 5],
       [1, 0, 0, 0, 2],
       [2, 0, 1, 0, 1],
       [9, 0, 0, 0, 1],
       [8, 5, 7, 9, 5]], dtype=int32)

# Array Manipulation

# reshape

In [99]:
arr = array(([4,1,2,3],
             [3,2,4,2],
             [3,6,5,7]))
# arr1 = np.arange(1,13).reshape(3,4)

# C-Style modify
# arr.reshape(2,6, order='C')[1, 2:] = 9 

# Fortran-Style not be modify
arr.reshape(2,6, order='F')[1, 2:] = 9 
arr


array([[4, 1, 2, 3],
       [3, 2, 4, 2],
       [3, 6, 5, 7]])

# resize

In [100]:
arr = np.arange(0,10).reshape(2,5)
arr.resize((5,2), refcheck=True)
arr1 = arr
arr1[4, 0] = -1
# arr1
arr1 == arr


array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

# transpose()

In [101]:
arr = array(([2,3,4,5],
             [3,2,3,5]))

arr.transpose()

arr.transpose() == arr.T

arr.transpose().shape == arr.shape[::-1] 
# arr.transpose().ndim

True

# swapaxes(axis1, axis2)

Swapaxes returns a view without copy of data  so when changes it affects on original data

In [110]:
arr.swapaxes(0,1)
# arr.swapaxes(0,1) == arr.T

# arr = np.arange(30).reshape((2,3,5))
# arr.swapaxes(1,2)
# # arr

arr = np.indices((4,5))
arr.swapaxes(1,2)[0][2:] = 9
arr

# arr.ndim
# arr

array([[[0, 0, 9, 9, 9],
        [1, 1, 9, 9, 9],
        [2, 2, 9, 9, 9],
        [3, 3, 9, 9, 9]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

# flatten(order='C')

It is a method used to converting multi-deminsional to 1D.

Changes on flatten 1D array, no affects on original array.

In [103]:
arr = np.arange(1,21).reshape(5,4)

arr_f = arr.flatten(order='C')

# arr.flatten(order='F')

# arr_copy = arr.copy()

# arr_copy[3:] = 0

# arr_copy

arr_f[4:] = 0
arr_f

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# ravel(order='C')

This also converting multi-dimensional to 1D but it provide much better efficieny than flatten.

Changes on ravel 1D array, also affects on original array.

In [104]:
arr = np.arange(10,20).reshape(5,2) 
arr_r = arr.ravel()
arr_r[4:] = -1
arr

array([[10, 11],
       [12, 13],
       [-1, -1],
       [-1, -1],
       [-1, -1]])

# squeeze()

returns an array with all unit length dimension squeezes out/ removes.

In [105]:
# arr = array(([2,3,1,34]))
# arr.squeeze()
# arr.ndim
arr.squeeze()
# arr.ndim



array([[10, 11],
       [12, 13],
       [-1, -1],
       [-1, -1],
       [-1, -1]])

# Fancy Indexing

In [106]:
arr = np.arange(20).reshape(4,5)
arr
arr[[0,2]][:, [4,2]]
# both are same
# arr[np.ix_([0,2], [4,2])]


array([[ 4,  2],
       [14, 12]])