# Array Calculation

In [2]:
import numpy as np
from numpy import array

# argsort(axis,kind)

In [3]:
arr = np.arange(-10,10).reshape(5,4)
arr.argsort(axis=0)
# arr.argsort(axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

# choose(index)
Choose column from different array calling index

In [4]:
arr 
np.choose(3,choices=arr)


array([2, 3, 4, 5])

# compress(condition=, axis=None, out=None)

If condition true then given axis based on result gives. False are ignorance.

In [5]:
arr = np.arange(5,25).reshape(5,4)
print(arr)
# pre-allocate conditions
cond = [True]*5
cond[1] = False
cond[4] = False

# output container creates to stored compressed result
output =  np.empty((4,4), dtype=arr.dtype)

np.compress(cond, arr, axis=0)

# output[[2,3], 1:3] = 0
# output

# arr
# # Rotated L -> Pattern 
# arr[[0,1,2,3,4],[0,0,0,0,0]] = 9
# arr[0] = 9

# arr[[1,2,3,4],[1,1,1,1]] = 8
# arr[1,1:] = 8

# arr[[2,3,4],[2,2,2]] = 7
# arr[2,2:] = 7

# arr[[3,4],[3,3]] = 6

# arr

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# diagonal(offset=0, axis1=0, axis2=1)

offset: Basically, offset is shifts the diagonal starting point.

In [6]:
arr = np.arange(1,26).reshape(5,5)
print(arr)
arr.diagonal(offset=0, axis1=-1, axis2=0)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([ 1,  7, 13, 19, 25])

# diag_indices(n) 
n -> shape of dimension of a square matrix


In [20]:
v = np.array([[3,7]])

a = np.zeros((v.size,v.size))
# np.full_like(a,39) 

x,y = np.diag_indices(v.shape[-1])
a[x,y] = 1
a

array([[1., 0.],
       [0., 1.]])

# diag(v) v-> 1D vector
v -> contains dimensions of a square matrix. 

It gives diagonal matrix and off-diagonal matrix element are zero.

In [8]:
v = np.arange(1,15)
np.diag(v)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 14]])

# nonzero()

In [9]:
arr.nonzero()

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4]))

# put(indices=, value=, mode='raise')

It affects on original array

In [10]:
arr.put(6, 10)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# ptp(axis=None, out=None)

It returns difference between max and min.

In [11]:
np.ptp(arr, axis=0)

array([20, 20, 20, 20, 20])

# clip(min=, max=, out=None)

In general, we can apply limits in array.

Use case:

Trianing model

Image processing (for fixed pxiel valid range)

Overal, It use prevents from exceeding range.

In [12]:
arr.clip(max=5)

np.clip(arr, min=1, max=100)

# stored clip result in output
output = np.empty((5,5), dtype=arr.dtype)

np.clip(arr, min=5, max=50, out=output)
output

array([[ 5,  5,  5,  5,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# conjugates(out=None)

In [13]:
complex_arr = np.array(([3+2j,1-9j],
                        [2+1j, 0+7j]))
np.conjugate(2+3j)
np.conjugate(complex_arr)


array([[3.-2.j, 1.+9.j],
       [2.-1.j, 0.-7.j]])

0.7337993857053429
