Indexing on array

In [ ]:
import numpy as np
x = np.array(([3,5,3],[1,3,5],[9,8,7]))
y = np.array(([8,9,0],[8,9,7],[5,6,7]))
print(x*y)
print(np.prod(x))
# changing element from its position (n,m)
x[1,1] = 91
print(x)

[[24 45  0]
 [ 8 27 35]
 [45 48 49]]
340200
[[ 3  5  3]
 [ 1 91  5]
 [ 9  8  7]]


Get silicing result from array

In [3]:
print(x[1][::-1]) #rotating the given array
x[1,-1] = 90
print(x)
print(np.prod(x[-1]))

x = x[::-1]
print(x)
print(np.sum(x[-1]))

[5 3 1]
[[ 9  5  3]
 [ 1  3 90]
 [ 9  8  7]]
504
[[ 9  8  7]
 [ 1  3 90]
 [ 9  5  3]]
17


In [4]:
# import numpy as np
# x = np.array(([4,2,5,2,5],[3,2,5,6,9]))
# x[0,4] = 10 # [row,col]
# print(x)

Get silice result

In [5]:
import numpy as np
x = np.array([[4,3,32,6,5,0]])
print(x[:]) 

[[ 4  3 32  6  5  0]]


In [6]:
print(x[:-1:2])

[]


In [7]:
# np.concatenate((x, [[3,2,15,6,1,8]]))
print(np.concatenate((x, [[3,2,15,6,1,8]])))
print(x)

[[ 4  3 32  6  5  0]
 [ 3  2 15  6  1  8]]
[[ 4  3 32  6  5  0]]


In [15]:
arr = x.copy()
arr[0,0] = 0
print(arr)

[[ 0  5  3]
 [ 1 91  5]
 [ 9  8  7]]
