In [1]:
import numpy as np
from numpy import array

In [2]:
matrix = np.matrix(([2,1,4,5],
                    [2,3,13,4]))

arr = array(matrix, subok=True, order='F')  # use of subok transformation of type if true -> numpy.matrix if false numpy.ndarray
type(arr)  
arr

matrix([[ 2,  1,  4,  5],
        [ 2,  3, 13,  4]])

# asarray()

avoid copy and memory speed performance.

This is exactly same as array, in this array copy is False and subok is always False.

In [3]:
arr = np.asarray(([3,2,4,1,2],
                  [1,5,3,1,2],
                  [1,2,3,4,5]))
arr_c = arr.copy()

arr_c[0] = 10
arr_c.flags

np.matrix(arr).flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# asanyarray (object, dtype=None, order=None)

Avoid copy and preserved subclass

Use: When subclass behavior must be preserved 

In [4]:
arr = np.asanyarray(([2,3,1],[5,3,6],[1,0,9]), order='F')
np.isfortran(arr)

True

In [5]:
arr = np.arange(1,21, dtype=float).reshape((5,4))
print(arr)
arr.sum(axis=-1) # row-wise sum [1 or -1] and column-wise sum [0 or -2]

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]]


array([10., 26., 42., 58., 74.])

# empty_like(arr)

In [6]:
np.empty_like(arr, order='C')

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [7]:
zero = np.ones((9,3), dtype=np.int32)
zero

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

# fromfile(file='file.txt', dtype=int, count=10, sep=',')

In [8]:
np.fromfile(file='file.txt', dtype=int, count=10, sep=',')

array([ 4,  2,  2, 90, 32,  3,  2, 45, 56, 32])

# frombuffer (buffer, dtype=intp, count=-1, offset=0)

buffer is memory address of stored data

In [9]:
arr_buff = np.frombuffer(buffer=arr,  dtype=np.intp)

arr_buff.astype

<function ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)>

In [10]:
import pickle
filename = 'file_binary_data.pkl'
with open(filename, 'rb')as f:
    print(pickle.load(f))


{'Model': 321, 'MonoDB': 'SQL Lite', 'Byte': 'Bit', 'Serialization': 'Pickling'}


# indices(dimension, dtype=intp)

Used for multi-dimension

In [11]:
np.indices((2,4,4,5,9,10,11)).ndim

8

# fromfunction (function, dimensions, **kwargs)

# fromiter(arr, dtype=)

In [12]:
arr = np.arange(1,9)
np.fromiter(arr, dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8.])

# dot(a,b)

Matrix dot product of between two array.

In [13]:
arr = np.arange(1,5).reshape(2,2)
np.dot(arr,arr)  #a -> row * b-> column

array([[ 7, 10],
       [15, 22]])

# vdot(a,b)
flattern into one-dimension vector or inner product or             sum(a_row * b_row)

In [14]:
np.vdot(arr,arr)  # -> 30

np.int64(30)

# outer(a,b)

Each element of a multiplies with every single element of b.

It used expand the matrices 

In [15]:
arr1 = array(([1,2,3,3],[2,3,1,4]))
np.outer(arr,arr)
# arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

# inner(a,b)
 
inner -> collapse -> sum products along last axis -> scalar or smaller matrix

OR

Every single row element of a multiply with every single row element of b and then sum it.  means first row of a multiply with each row of b and so on.

In [16]:
np.inner(arr,arr)

array([[ 5, 11],
       [11, 25]])

# tensordot(a,b,axes=((-1,0)))

axes is called multiple dimensions

-1 -> shape of last dimension of a means first row of all columns 

we can also interchange axes .

0 -> shape of first dimension of b means every single row of all elements

when axes is 0 then expand the matrix (every single elements of a multiply with every single element of b)

when axes > 0 then collapse means values are combining along the axes.

Behind sense: last_dimension * first_dimension and sum it

In [17]:
arr =np.arange(1,9).reshape(4,2)

np.tensordot(arr,arr1, axes=((-1,0)))  #every single row of elements of a multiplies with every single column of elements
# arr1.shape

np.tensordot(arr1,arr, axes=((0,-1)))  #every single column of elements of a multiplies with every single row of elements


# np.tensordot(arr,arr1, axes=0)  #  same like as outer
# np.tensordot(arr,arr1, axes=1)

array([[ 5, 11, 17, 23],
       [ 8, 18, 28, 38],
       [ 5, 13, 21, 29],
       [11, 25, 39, 53]])

# cross (a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)

In [18]:
# arr = np.arange(10,28).reshape((2,3,3))
arr = np.array(([2,-1,3],[1,5,3]))
arr1 = np.array(([4,9,2],[4,2,5]))
np.cross(arr,arr1, axis=1)
# arr

array([[-29,   8,  22],
       [ 19,   7, -18]])

# allclose(a,b, rtol=10^-8, atol=10^-5)

|a − b| < atol + rtol |b| .

So this is used to check toleraces.
Tolerance means if tiny threshold error found then  minimum changes required to continue the computation. 

In [19]:
a = np.array([0,0])
b = np.array([0,0])
np.allclose(a,b, rtol=10**-8, atol=10**-5)

True