In [1]:
import numpy as np

# Contiguous memory layout

In [6]:
# [1,2,3,4]  -> layout  
arr = np.array(([2,1,2,0],
                [1,23,5,6],
                [5,4,45,6],
                [0,3,4,6]))
arr.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# C_Style N-dimensional array

Indexing -> left increament first  (means column)

In [3]:
print(arr)
arr.flags

[[ 2  1  2  0]
 [ 1 23  5  6]
 [ 5  4 45  6]
 [ 0  3  4  6]]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# Fortran_Style N-dimensional array


Indexing ->right increments first (means row)

In [4]:
arr1 = arr.T
print(arr1)
arr1.flags

[[ 2  1  5  0]
 [ 1 23  4  3]
 [ 2  5 45  4]
 [ 0  6  6  6]]


  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False