In [ ]:
import numpy as np
file = np.genfromtxt('data.txt', delimiter=',')
# with open('data.txt')as f:
#     for i,v in enumerate(f.readlines(),start=1):
#         print(f"{i}. {v}")

# print(file)

In [ ]:
matrix = np.random.randint(90, size=((6,5)))
# print(matrix)
# matrix = np.array(([1,3,5,2],[3,4,6,7]))
# x = matrix[2,0]
# y = matrix[2,1]
# z = matrix[3,0]
# p = matrix[3,1]

print(np.full_like(matrix,9))

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [ ]:
puzzel = np.random.randint(1,30,size=((8,8)))
print(puzzel)

pzz = puzzel[2:-2, :2] 
print(pzz)

# pzz = puzzel[2:-3, :-3]
# pzz1 = puzzel[3:-2, :-3]
# s = np.concatenate((pzz, pzz1))
# print()

# print(pzz)
# print(pzz1)
# print()
# print(s)


[[27 24  6 13 20 26 22 26]
 [17 29 13 17  2  9  1 28]
 [16  4 27 21 13 27 25 20]
 [ 1 17  4 22  5  9  9 12]
 [11 27 25 29 10 10 28 17]
 [24 24  3 14  9 11  7 14]
 [ 9 19  6 27 13 24  1  3]
 [20 21 10 14 15 25 12 17]]
[[16  4]
 [ 1 17]
 [11 27]
 [24 24]]


In [ ]:
#matrix indices calling elements
# First select indices of array then pick element of that array
puzz = puzzel[[0,1,2,3], [1,2,3,4]]
print(puzz)

pzz = puzzel[[0,6,7], -2:]
print(pzz)
# to change any paticular position element
puzzel[1,2] = 120
print(puzzel)

[  24 1200   21    5]
[[22 26]
 [ 1  3]
 [12 17]]
[[ 27  24   6  13  20  26  22  26]
 [ 17  29 120  17   2   9   1  28]
 [ 16   4  27  21  13  27  25  20]
 [  1  17   4  22   5   9   9  12]
 [ 11  27  25  29  10  10  28  17]
 [ 24  24   3  14   9  11   7  14]
 [  9  19   6  27  13  24   1   3]
 [ 20  21  10  14  15  25  12  17]]


In [ ]:
pzz = puzzel[2:4, -2:]
print(pzz)

[[25 20]
 [ 9 12]]
