In [28]:
import numpy as np

# Student Performance Dataset (Data Representation)

In [60]:
# students marks of five subjects (Math, Physics, Chemistry, Computer, English)
matrix = np.array((
                [80,75,90,75,95],
                [60,70,65,69,80],
                [90,88,85,65,86]))

print(matrix)
# Rows represent what?
# Each row represents a student marks for all subject.

# Columns represent what?
# Each column represents different sutudents same subject marks. 

print(matrix.shape)
print(matrix.ndim)

[[80 75 90 75 95]
 [60 70 65 69 80]
 [90 88 85 65 86]]
(3, 5)
2


# Compute the average score per subject (column-wise mean)

In [ ]:
col_mean = matrix.mean(axis=0)
print(col_mean)

[76.66666667 77.66666667 80.         69.66666667 87.        ]


# Compute the average score per student (row-wise mean)

In [61]:
row_mean = matrix.mean(axis=1)
print(row_mean)

[83.  68.8 82.8]


# Feature Scaling (Normalization in Practice)

In [ ]:
data = np.array(([90,60,98,45],
                 [66,45,67,89],
                 [56,45,78,89],
                 [54,67,89,45]))

# Column-wise normalization
col_normalization = (data - data.min(axis=0))/(data.max(axis=0) - data.min(axis=0))
print(col_normalization)

(4, 4)
[[1.         0.68181818 1.         0.        ]
 [0.33333333 0.         0.         1.        ]
 [0.05555556 0.         0.35483871 1.        ]
 [0.         1.         0.70967742 0.        ]]
