In [1]:
import numpy as np

# 🔹 LEVEL 1 — Foundations (1D & 2D intuition)


1. Ans: (4,)
2. Ans: 2
3. Ans: (3,5)
4. Ans: (2,)
5. Ans: (10,)
6. Ans: (2,5)
7. Ans: (4,2)
8. Ans: (3,1)
9. Ans: (1,3)
10. Ans: (3,8)

# 🔹 LEVEL 2 — Matrix Operations

11. Ans: 

# ✅ Set A: Shape & Dimensionality

# 1. 
Create:

In [2]:
# Scalar
scal = np.array(4+5j)
print(scal.shape)  # -> () because complex number  has no shape, even any a numberic value like int,float it shape be empty that is ()
print(scal.ndim) # -> 0 because a numberic value has no any dimension
print(scal.size) # -> 1
print(scal.dtype) # -> complex 128

# A 1D vector of length 5
vec = np.array([1,2,3,4,5])
print(vec.shape) # -> (5,)
print(vec.ndim) # -> 1
print(vec.size) # -> 5
print(vec.dtype) # -> int 64

# A 2D matrix (3*4)
matrix = np.array(([3,1,4,2],
                   [5,7,8,6],
                   [4,6,2,1]))
print(matrix.size) # -> 12

# A 3D matrix (2*3*4)
tensor = np.arange(1,25).reshape((2,3,4))
print(tensor.dtype) # -> int 64
print(tensor.shape) # -> (2,3,4)
print(tensor.ndim) # -> 3

()
0
1
complex128
(5,)
1
5
int64
12
int64
(2, 3, 4)
3


# 2.
 Convert a 1D array of 12 elements into:

In [3]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

arr1 = np.arange(1,13).reshape((2,2,3))
print(arr1)

arr2 = np.arange(1,13).reshape(4,3)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 3.
Without using reshape, turn a (3×4) matrix into (4×3).

In [4]:
arr = np.array(([ 1 , 2 , 3 , 4],
                [ 5 , 6 , 7 , 8],
                [ 9 ,10, 11 ,12]))

# arr.transpose() == arr.T
print(arr.transpose())
# or
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# 4.
Explain:

Q1. Why a row vector (1×5) is different from (5,) shape?

Ans: Because this row (1*5) vector is reshaped (means arranged) of the original vector shape and (5,) is own shape there is no reshape to do it.

Q2. What happens during broadcasting in (3,1) + (1,4)?

Ans: 3 multiplication to 1 and 1 multiplication to 4 that is (3*1, 1*4) = (3,4)

# ✅ Set B: Indexing Mastery

5. From a 5×5 matrix:

In [5]:
matrix = np.arange(1,26).reshape(5,5)

# Extract middle row
matrix[2]
# or
matrix[2,:]

# Extract middle column
matrix[[0,1,2,3,4],2]  #this is also called fancy indexing
# # or
matrix[:,2]

# Extract diagonal
np.diagonal(matrix, offset=0, axis1=0,axis2=1)

# Extract top-right 2×2 block
matrix[[0,1], 3:]


array([[ 4,  5],
       [ 9, 10]])

6. Using boolean indexing:

In [6]:
mat = np.random.randint(-5,15, size=((5,4)))
mat[mat<0] = 0
mat

array([[ 0,  3, 13,  1],
       [ 8,  0, 10, 12],
       [ 3,  0,  7,  6],
       [ 0,  0, 10,  7],
       [ 0,  7,  9,  0]], dtype=int32)

7. Use integer indexing to rearrange rows arbitrarily.

Arbitrary means select/pick any as per our choice.

In [7]:
matrix[[1,3,0,4,2], :]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15]])

# 🔵 PHASE 2 — Operations & Broadcasting (Chapter 9)

Self practice:

In [ ]:
a = np.array(([2,3,1],  #input array with larger ndim shape
           [4,3,1],
           [2,4,5]))
b = np.array(([2],[1],[3]))  # smaller ndim shape
print(a.shape , b.shape)

print(a+b)
# a+b == b+a
b.ndim
b.size


np.arange(1,10).reshape(3,3)+np.arange(9).reshape(3,3)

(3, 3) (3, 1)
[[4 5 3]
 [5 4 2]
 [5 7 8]]


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])