In [1]:
import numpy as np

In [2]:
# Vertical stacking

X = np.array(([1,2], 
              [3,2]))
Y = np.array(([3,1],
              [3,4]))
print(np.vstack([X,Y])) #use both parentheses and square barcket

# Horizontal stacking
print(np.hstack([X,Y])) #use both parentheses and square barcket

[[1 2]
 [3 2]
 [3 1]
 [3 4]]
[[1 2 3 1]
 [3 2 3 4]]


# Matrix Multiplication

In [3]:
np.dot(X,Y)
np.multiply(X,Y)

array([[3, 2],
       [9, 8]])

# Boardcasting

In [40]:
a = np.arange(1,5)  # no. of rows diff = 5-1= 4
b = np.arange(4,9)  # no. of column diff = 9-4= 5
# 

print(a.shape)

(4,)


# Adding new axis

In [ ]:
print(a[:,np.newaxis])
a[:,np.newaxis]*b

# print('\n',b[:, np.newaxis])

[[1]
 [2]
 [3]
 [4]]


array([[ 4,  5,  6,  7,  8],
       [ 8, 10, 12, 14, 16],
       [12, 15, 18, 21, 24],
       [16, 20, 24, 28, 32]])